#!/usr/bin/env bash

### General variables
AZURE_LOCATION=${AZURE_LOCATION:-"westeurope"}
#ARM_SUBSCRIPTION_ID=""
#ARM_TENANT_ID=""

# the Azure DevOps organization url
AZURE_DEVOPS_ORG_URL=${AZURE_DEVOPS_ORG_URL:-${AZDO_ORG_SERVICE_URL}}

# the Azure DevOps organization Personal Access Token - required for Terraform, optional for Azure CLI
AZURE_DEVOPS_EXT_PAT=${AZURE_DEVOPS_EXT_PAT:-${AZDO_PERSONAL_ACCESS_TOKEN}}

# the Personal Access Token to authenticate to GitHub
AZURE_DEVOPS_EXT_GITHUB_PAT=${AZURE_DEVOPS_EXT_GITHUB_PAT:-${AZDO_GITHUB_SERVICE_CONNECTION_PAT}}

# a suffix to append to most names
SUFFIX=${SUFFIX:-"demo"}

### Service Principals and Groups
INFRA_SP_NAME=${INFRA_SP_NAME:-"spn-infra-${SUFFIX}"}
DATA_SP_NAME=${DATA_SP_NAME:-"spn-data-${SUFFIX}"}
PROJECT_GROUP_NAME=${PROJECT_GROUP_NAME:-"Project Group ${SUFFIX}"}

### Databricks resources
DATABRICKS_RESOURCE_GROUP_NAME=${DATABRICKS_RESOURCE_GROUP_NAME:-"rg-databricks-${SUFFIX}"}
KEY_VAULT_NAME=${KEY_VAULT_NAME:-"kv-main-${SUFFIX}"}
SECRET_NAME="dataServicePrincipalClientSecret"

### Terraform resources
# remove if not using Terraform
TF_RESOURCE_GROUP_NAME=${TF_RESOURCE_GROUP_NAME:-"rg-terraform-${SUFFIX}"}
TF_STORAGE_ACCOUNT_NAME=${TF_STORAGE_ACCOUNT_NAME:-"stterraform123${SUFFIX}"}
TF_CONTAINER_NAME=${TF_CONTAINER_NAME:-"tfstate"}

### Azure DevOps variables
AZURE_DEVOPS_PROJECT_NAME=${AZURE_DEVOPS_PROJECT_NAME:-"my-project-${SUFFIX}"}

AZURE_DEVOPS_INFRA_ARM_ENDPOINT_NAME=${AZURE_DEVOPS_INFRA_ARM_ENDPOINT_NAME:-"my-infra-endpoint-${SUFFIX}"}
AZURE_DEVOPS_DATA_ARM_ENDPOINT_NAME=${AZURE_DEVOPS_DATA_ARM_ENDPOINT_NAME:-"my-data-endpoint-${SUFFIX}"}

AZURE_DEVOPS_GITHUB_ENDPOINT_NAME=${AZURE_DEVOPS_GITHUB_ENDPOINT_NAME:-"my-git-endpoint-${SUFFIX}"}
AZURE_DEVOPS_GITHUB_REPO_URL=${AZURE_DEVOPS_GITHUB_REPO_URL:-"https://github.com/alexandruanghel/azdo-databricks"}
AZURE_DEVOPS_GITHUB_BRANCH=${AZURE_DEVOPS_GITHUB_BRANCH:-"master"}

AZURE_DEVOPS_INFRA_PIPELINE_NAME=${AZURE_DEVOPS_INFRA_PIPELINE_NAME:-"my-infra-pipeline-${SUFFIX}"}
AZURE_DEVOPS_INFRA_PIPELINE_PATH_CLI=${AZURE_DEVOPS_INFRA_PIPELINE_PATH:-"pipelines/azure-pipelines-infra-with-azure-cli.yml"}
AZURE_DEVOPS_INFRA_PIPELINE_PATH_TF=${AZURE_DEVOPS_INFRA_PIPELINE_PATH:-"pipelines/azure-pipelines-infra-with-terraform.yml"}
AZURE_DEVOPS_DATA_PIPELINE_NAME=${AZURE_DEVOPS_DATA_PIPELINE_NAME:-"my-data-pipeline-${SUFFIX}"}
AZURE_DEVOPS_DATA_PIPELINE_PATH=${AZURE_DEVOPS_DATA_PIPELINE_PATH:-"pipelines/azure-pipelines-data-factory-msi.yml"}
#AZURE_DEVOPS_DATA_PIPELINE_PATH=${AZURE_DEVOPS_DATA_PIPELINE_PATH:-"pipelines/azure-pipelines-data-factory-accesstoken.yml"}

### Terraform variables
export TF_VAR_AZURE_LOCATION="${AZURE_LOCATION}"

export TF_VAR_INFRA_SP_NAME="${INFRA_SP_NAME}"
export TF_VAR_DATA_SP_NAME="${DATA_SP_NAME}"
export TF_VAR_PROJECT_GROUP_NAME="${PROJECT_GROUP_NAME}"

export TF_VAR_DATABRICKS_RESOURCE_GROUP_NAME="${DATABRICKS_RESOURCE_GROUP_NAME}"
export TF_VAR_KEY_VAULT_NAME="${KEY_VAULT_NAME}"
export TF_VAR_SECRET_NAME="${SECRET_NAME}"

export TF_VAR_TF_RESOURCE_GROUP_NAME="${TF_RESOURCE_GROUP_NAME}"
export TF_VAR_TF_STORAGE_ACCOUNT_NAME="${TF_STORAGE_ACCOUNT_NAME}"
export TF_VAR_TF_CONTAINER_NAME="${TF_CONTAINER_NAME}"

export TF_VAR_AZURE_DEVOPS_PROJECT_NAME="${AZURE_DEVOPS_PROJECT_NAME}"
export TF_VAR_AZURE_DEVOPS_INFRA_ARM_ENDPOINT_NAME="${AZURE_DEVOPS_INFRA_ARM_ENDPOINT_NAME}"
export TF_VAR_AZURE_DEVOPS_DATA_ARM_ENDPOINT_NAME="${AZURE_DEVOPS_DATA_ARM_ENDPOINT_NAME}"
export TF_VAR_AZURE_DEVOPS_GITHUB_ENDPOINT_NAME="${AZURE_DEVOPS_GITHUB_ENDPOINT_NAME}"
export TF_VAR_AZURE_DEVOPS_GITHUB_REPO_URL="${AZURE_DEVOPS_GITHUB_REPO_URL}"
export TF_VAR_AZURE_DEVOPS_GITHUB_BRANCH="${AZURE_DEVOPS_GITHUB_BRANCH}"
export TF_VAR_AZURE_DEVOPS_INFRA_PIPELINE_NAME="${AZURE_DEVOPS_INFRA_PIPELINE_NAME}"
export TF_VAR_AZURE_DEVOPS_INFRA_PIPELINE_PATH="${AZURE_DEVOPS_INFRA_PIPELINE_PATH_TF}"
export TF_VAR_AZURE_DEVOPS_DATA_PIPELINE_NAME="${AZURE_DEVOPS_DATA_PIPELINE_NAME}"
export TF_VAR_AZURE_DEVOPS_DATA_PIPELINE_PATH="${AZURE_DEVOPS_DATA_PIPELINE_PATH}"
